// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxqazwlpoxjnhhdflibz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4cWF6d2xwb3hqbmhoZGZsaWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MzQzMzUsImV4cCI6MjA2MDExMDMzNX0.gJ8dsEppTuhVlA4v0F_SJ_Hr0_bCM0qpGMiDInGQzyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);